name: Actor
main: com.insofar.actor.ActorPlugin
version: 0.8
website: http://dev.bukkit.org/server-mods/actor/
description: >
             Actor Plugin by Joshua Weinberg
softdepend: [Vault]
commands:
   actor:
      description: Root command for ActorPlugin
      usage: /actor

permissions:
   Actor.*:
      description: Gives access to all Actor commands and permissions
      default: op
      children:
         Actor.command.record: true
         Actor.command.cut: true
         Actor.command.hire: true
         Actor.command.dub: true
         Actor.command.fire: true
         Actor.command.action: true
         Actor.command.actionrec: true
         Actor.command.loop: true
         Actor.command.reset: true
         Actor.command.saveactor: true
         Actor.command.savescene: true
         Actor.command.loadactor: true
         Actor.command.loadscene: true
   Actor.command.*:
      description: Gives access to all Actor commands
      default: op
      children:
         Actor.command.record: true
         Actor.command.cut: true
         Actor.command.hire: true
         Actor.command.dub: true
         Actor.command.fire: true
         Actor.command.action: true
         Actor.command.actionrec: true
         Actor.command.loop: true
         Actor.command.reset: true
         Actor.command.saveactor: true
         Actor.command.savescene: true
         Actor.command.loadactor: true
         Actor.command.loadscene: true
   Actor.command.record:
      description: Allows user to use record command
      default: op
   Actor.command.cut:
      description: Allows user to use cut command
      default: op
   Actor.command.hire:
      description: Allows user to use hire command
      default: op
   Actor.command.dub:
      description: Allows user to use dub command
      default: op
   Actor.command.fire:
      description: Allows user to use fire command
      default: op
   Actor.command.action:
      description: Allows user to use action command
      default: op
   Actor.command.actionrec:
      description: Allows user to use actionrec command
      default: op
   Actor.command.loop:
      description: Allows user to use loop command
      default: op
   Actor.command.reset:
      description: Allows user to use reset command
      default: op
   Actor.command.saveactor:
      description: Allows user to use saveactor command
      default: op
   Actor.command.savescene:
      description: Allows user to use savescebe command
      default: op
   Actor.command.loadactor:
      description: Allows user to use loadactor command
      default: op
   Actor.command.loadscene:
      description: Allows user to use loadscene command
      default: op